export enum IpcEvent {
  WINDOW_OPENED = 'WINDOW_OPENED',
  POWER_AWAKE = 'POWER_AWAKE',

  LAUNCH_SETTINGS_REQUEST = 'LAUNCH_SETTINGS_REQUEST',
  LAUNCH_SETTINGS_REPLY = 'LAUNCH_SETTINGS_REPLY',
  LAUNCH_SETTINGS_SET = 'LAUNCH_SETTINGS_SET',

  CHECK_FOR_UPDATES_REQUEST = 'CHECK_FOR_UPDATES_REQUEST',
  QUIT_AND_INSTALL_UPDATE_REQUEST = 'QUIT_AND_INSTALL_UPDATE_REQUEST',
  CHECKING_FOR_UPDATE = 'CHECKING_FOR_UPDATE',
  UPDATE_AVAILABLE = 'UPDATE_AVAILABLE',
  UPDATE_NOT_AVAILABLE = 'UPDATE_NOT_AVAILABLE',
  UPDATE_DOWNLOADED = 'UPDATE_DOWNLOADED',
  UPDATE_DOWNLOADING = 'UPDATE_DOWNLOADING',
  UPDATE_ERROR = 'UPDATE_ERROR'
}
