
export enum IpcEvent {
  WINDOW_OPENED = 'WINDOW_OPENED',
  LAUNCH_SETTINGS_REQUEST = 'LAUNCH_SETTINGS_REQUEST',
  LAUNCH_SETTINGS_REPLY = 'LAUNCH_SETTINGS_REPLY',
  LAUNCH_SETTINGS_SET = 'LAUNCH_SETTINGS_SET'
}